/* SUB Tool — preload：以 contextBridge 安全暴露桌面能力給前端 (window.subtool) */
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('subtool', {
  isDesktop: true,
  status:       () => ipcRenderer.invoke('app:status'),
  fileURL:      (p) => { if(typeof p!=='string') throw new TypeError('path must be a string'); return ipcRenderer.invoke('fs:fileURL', p); },
  stat:         (p) => { if(typeof p!=='string') throw new TypeError('path must be a string'); return ipcRenderer.invoke('fs:stat', p); },
  openMedia:    () => ipcRenderer.invoke('dialog:openMedia'),
  openAudio:    () => ipcRenderer.invoke('dialog:openAudio'),
  openProject:  () => ipcRenderer.invoke('dialog:openProject'),
  saveProject:  (name, b64) => ipcRenderer.invoke('dialog:saveProject', { name, b64 }),
  importSub:    (kind) => ipcRenderer.invoke('dialog:importSub', kind),
  exportSub:    (name, b64, ext) => ipcRenderer.invoke('dialog:exportSub', { name, b64, ext }),
  exportDirectory: (files) => ipcRenderer.invoke('dialog:exportDirectory', files),
  probe:        (p) => { if(typeof p!=='string') throw new TypeError('path must be a string'); return ipcRenderer.invoke('ffprobe', p); },
  makeProxy:    (p, duration) => { if(typeof p!=='string') throw new TypeError('path must be a string'); return ipcRenderer.invoke('ffmpeg:proxy', { path: p, duration }); },
  extractAudio: (p, idx, duration, codec) => { if(typeof p!=='string') throw new TypeError('path must be a string'); return ipcRenderer.invoke('ffmpeg:extractAudio', { path: p, idx, duration, codec }); },
  waveAudio:    (p, duration) => { if(typeof p!=='string') throw new TypeError('path must be a string'); return ipcRenderer.invoke('ffmpeg:waveAudio', { path: p, duration }); },
  cleanupAudio: (p) => { if(typeof p!=='string') throw new TypeError('path must be a string'); return ipcRenderer.invoke('ffmpeg:cleanup', { path: p }); },
  ingest:       (opts) => ipcRenderer.invoke('ffmpeg:ingest', opts),
  streamIngest: (opts) => ipcRenderer.invoke('ffmpeg:streamIngest', opts),
  readB64:      (p) => { if(typeof p!=='string') throw new TypeError('path must be a string'); return ipcRenderer.invoke('fs:readB64', p); },
  writeProject: (p, b64) => { if(typeof p!=='string') throw new TypeError('path must be a string'); return ipcRenderer.invoke('fs:writeProject', { path: p, b64 }); },
  cacheInfo:    () => ipcRenderer.invoke('cache:info'),
  cacheCleanOrphans: () => ipcRenderer.invoke('cache:cleanOrphans'),
  configLoad:   () => ipcRenderer.invoke('config:load'),
  configSave:   (data) => ipcRenderer.invoke('config:save', data),
  keysLoad:     () => ipcRenderer.invoke('keys:load'),
  keysSave:     (data) => ipcRenderer.invoke('keys:save', data),
  cacheClearAll: (src) => ipcRenderer.invoke('cache:clearAll', src),
  getStartupFile: () => ipcRenderer.invoke('app:getStartupFile'),
  onAppRequestClose: (cb) => ipcRenderer.on('app:request-close', () => cb()),
  closeApp: () => ipcRenderer.invoke('app:close'),
  onOpenFile:    (cb) => ipcRenderer.on('app:open-file', (e, path) => cb(path)),
  onProgress:   (cb) => ipcRenderer.on('task-progress', (e, d) => cb(d)),
  mpv: {
    detect:    ()      => ipcRenderer.invoke('mpv:detect'),
    launch:    (opts)  => ipcRenderer.invoke('mpv:launch', opts),
    seek:      (t)     => ipcRenderer.invoke('mpv:seek', t),
    play:      ()      => ipcRenderer.invoke('mpv:play'),
    pause:     ()      => ipcRenderer.invoke('mpv:pause'),
    mute:      (v)     => ipcRenderer.invoke('mpv:mute', v),
    rate:      (r)     => ipcRenderer.invoke('mpv:rate', r),
    setBounds: (b)     => ipcRenderer.invoke('mpv:setBounds', b),
    show:      (v)     => ipcRenderer.invoke('mpv:show', v),
    subSet:    (ass)   => ipcRenderer.invoke('mpv:subSet', ass),
    quit:      ()      => ipcRenderer.invoke('mpv:quit'),
    onEvent:   (cb)    => { ipcRenderer.removeAllListeners('mpv:event'); ipcRenderer.on('mpv:event', (_, d) => cb(d)); },
  },
});
