/* SUB Tool — 字幕格式 解析 / 序列化（SRT / ASS / Encore / TXT） */
import { clamp } from './util.js';
import { secToSRT, secToASS, secToEncore, srtToSec, assToSec, encoreToSec } from './time.js';

/* ===== 2. 字幕格式 解析 / 序列化 ====================================== */
const SubFormats = {
  /* ---- SRT ---- */
  parseSRT(text){
    const out=[]; const blocks=text.replace(/\r/g,'').split(/\n{2,}/);
    for(const blk of blocks){
      const lines=blk.split('\n');
      let i=0; while(i<lines.length && /^\s*\d+\s*$/.test(lines[i]))i++;
      const tline=lines[i]; if(!tline||!tline.includes('-->'))continue;
      const [a,b]=tline.split('-->');
      const start=srtToSec(a), end=srtToSec(b);
      const txt=lines.slice(i+1).join('\n').trim();
      out.push({start,end,text:txt});
    }
    return out;
  },
  toSRT(cues,fps){
    return cues.filter(c=>c.timed!==false).map((c,i)=>
      `${i+1}\n${secToSRT(c.start)} --> ${secToSRT(c.end)}\n${c.text||''}`).join('\n\n')+'\n';
  },
  /* ---- ASS ---- */
  parseASS(text){
    const out=[]; const lines=text.replace(/\r/g,'').split('\n');
    let fmt=null;
    for(const ln of lines){
      const t=ln.trim();
      if(/^Format:/i.test(t) && /Start/i.test(t) && /Text/i.test(t)){
        fmt=t.replace(/^Format:\s*/i,'').split(',').map(s=>s.trim().toLowerCase());
      }
      if(/^Dialogue:/i.test(t)){
        const rest=t.replace(/^Dialogue:\s*/i,'');
        const f=fmt||['layer','start','end','style','name','marginl','marginr','marginv','effect','text'];
        const nText=f.length; // 以欄位數切，text 取剩餘
        const parts=splitN(rest,nText-1);
        const rec={}; f.forEach((k,idx)=>rec[k]=parts[idx]!==undefined?parts[idx]:'');
        let raw=rec.text||'';
        const txt=raw.replace(/\{[^}]*\}/g,'').replace(/\\N/gi,'\n').replace(/\\h/g,' ').trim();
        let track=0;
        const nm=(rec.name||'').match(/atg?(\d+)/i); if(nm)track=Math.max(0,+nm[1]-1);
        else if(/^\d+$/.test(rec.layer))track=clamp(+rec.layer,0,9);
        out.push({start:assToSec(rec.start),end:assToSec(rec.end),text:txt,track});
      }
    }
    return out;
  },
  toASS(cues,fps,tracks=[],vw=1920,vh=1080, ww=1920, vww=1000, vwh=562){
    const head=
`[Script Info]
; Script generated by SUB Tool
ScriptType: v4.00+
WrapStyle: 0
Collisions: Normal
PlayResX: ${vww}
PlayResY: ${vwh}
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
`;
    let styles = '';
    const defFont = "思源黑體";
    const hexToAss = (hex) => {
      if (!hex) return '&H00FFFFFF';
      const c = hex.replace('#', '');
      if (c.length !== 6) return '&H00FFFFFF';
      return `&H00${c.slice(4,6)}${c.slice(2,4)}${c.slice(0,2)}`;
    };

    const targetPx = Math.max(14, Math.min(36, ww * 0.025));
    const baseFontSize = Math.round(targetPx);
    const spacing = 1.0;
    const defMarginV = Math.round(vwh * 0.1);
    if (!tracks || !tracks.length) {
      styles += `Style: Default,${defFont},${baseFontSize},&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,1,0,0,0,100.0,100.0,${spacing},0.0,1,2,0,2,135,135,${defMarginV},1\n`;
    } else {
      tracks.forEach((tk, i) => {
        const fs = Math.round(baseFontSize * (tk.fontScale || 1));
        const pp = tk.posPct != null ? tk.posPct : 10;
        const mv = Math.round(vwh * (pp / 100));
        const col = hexToAss(tk.color || '#ffffff');
        styles += `Style: Track${i},${defFont},${fs},${col},&H00FFFFFF,&H00000000,&H00000000,1,0,0,0,100.0,100.0,${spacing},0.0,1,2,0,2,135,135,${mv},1\n`;
      });
      styles += `Style: Default,${defFont},${baseFontSize},&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,1,0,0,0,100.0,100.0,${spacing},0.0,1,2,0,2,135,135,${defMarginV},1\n`;
    }

    const eventsHead = `\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n`;
    const body=cues.filter(c=>{
      if(c.timed===false) return false;
      const tk = c.track || 0;
      if(tracks && tracks[tk] && tracks[tk].visible === false) return false;
      return true;
    }).map(c=>{
      const txt=(c.text||'').replace(/\n/g,'\\N');
      const st = (tracks && tracks.length > (c.track||0)) ? `Track${c.track||0}` : 'Default';
      return `Dialogue: ${c.track||0},${secToASS(c.start)},${secToASS(c.end)},${st},atg${(c.track||0)+1},0,0,0,,${txt}`;
    }).join('\n');
    return head+styles+eventsHead+body+'\n';
  },
  /* ---- Adobe Encore ---- */
  parseEncore(text,fps,df=false){
    const out=[]; const lines=text.replace(/\r/g,'').split('\n');
    const re=/^\s*(\d{1,2}:\d{2}:\d{2}[:;]\d{2}|--:--:--:--)\s+(\d{1,2}:\d{2}:\d{2}[:;]\d{2}|--:--:--:--)\s+(.*)$/;
    let lastTime = 0;
    for(const ln of lines){
      const m=ln.match(re); if(!m)continue;
      const isUntimed = m[1]==='--:--:--:--' || m[2]==='--:--:--:--';
      let start = 0, end = 0;
      if(!isUntimed){
        start = encoreToSec(m[1],fps,df);
        end = encoreToSec(m[2],fps,df);
        lastTime = end;
      } else {
        start = lastTime;
        end = lastTime;
      }
      out.push({
        start, end,
        text: m[3].replace(/\s{2,}/g,'\n').trim(),
        timed: isUntimed ? false : undefined
      });
    }
    return out;
  },
  toEncore(cues,fps,df=false){
    return cues.map(c=>{
      if(c.timed===false) return `--:--:--:-- --:--:--:-- ${(c.text||'').replace(/\n/g,' ')}`;
      return `${secToEncore(c.start,fps,df)} ${secToEncore(c.end,fps,df)} ${(c.text||'').replace(/\n/g,' ')}`;
    }).join('\r\n')+'\r\n';
  },
  /* ---- 純文字 ---- */
  parseTXT(text){
    let t = 0;
    return text.replace(/\r/g,'').split('\n').map(l=>l.trim()).filter(l=>l.length)
      .map(l=>{ const c={start:t,end:t,text:l,timed:false}; t+=0.001; return c; });
  },
  toTXT(cues){
    return cues.map(c=>(c.text||'')).join('\n')+'\n';
  }
};
/* 把字串以逗號切成 n 段，第 n 段含其餘全部 */
function splitN(str,n){
  const out=[]; let i=0;
  for(let k=0;k<n;k++){ const j=str.indexOf(',',i); if(j<0){out.push(str.slice(i));return out;} out.push(str.slice(i,j)); i=j+1; }
  out.push(str.slice(i)); return out;
}

export { SubFormats, splitN };
