/* ==============================================================================
   SUB Tool — Module Architecture Protection ("src/formats.js")
   ==============================================================================
   【維護鐵律】本檔案已納入全專案終極防禦網。
   所有修改必須遵循專案的單向資料流與職責分離原則，嚴禁在此實作越權的 DOM 操作。
============================================================================== */
/* SUB Tool — 字幕格式 解析 / 序列化（SRT / ASS / Encore / TXT） */
import { clamp } from './util.js';
import { secToSRT, secToASS, secToEncore, srtToSec, assToSec, encoreToSec } from './time.js';
import { effStyle, styleToAssStyleLine, cueAssTags, cueAssPos, assJoinLines, assJoinVertical, verticalAssCols, assAlignN, assEscapeText, STYLE_ONLY_KEYS } from './substyle.js';

/* 舊版用 `//` 或兩個反斜線表示人工換行。URI 內的雙斜線是資料本身，
   包含 scheme 分隔與後續 path 中的 `//`，不可被誤切成多行。 */
function decodeLegacyLineBreaks(value){
  const text=String(value??'');
  const decodeChunk=chunk=>chunk.replace(/\\\\|\/\//g,'\n');
  // CJK 字幕常把網址直接接在全形標點後繼續寫；這些標點是 token 邊界，
  // 否則其後真正代表換行的 `//` 也會被整段誤保護。
  const uri=/\b[A-Za-z][A-Za-z0-9+.-]*:\/\/[^\s<>"'，。！？；：、（）【】「」『』《》〈〉\(\)\[\]\{\}]*/g;
  let out='',last=0,match;
  while((match=uri.exec(text))){
    out+=decodeChunk(text.slice(last,match.index));
    out+=match[0];
    last=match.index+match[0].length;
  }
  return out+decodeChunk(text.slice(last));
}

/* ASS Dialogue 文字不能用 `{...}` regex 處理：`\{`／`\}` 是使用者的字面括號，
   assEscapeText 也會以零寬空格切斷字面 `\N`、`\n`、`\h`。逐字掃描才能同時
   移除真正的 override tag、解控制碼，並把我們自己的跳脫還原。 */
function decodeAssDialogueText(value){
  const text=String(value??'');
  let out='';
  for(let i=0;i<text.length;){
    const ch=text[i];
    if(ch==='\\'){
      const next=text[i+1];
      if(next==='{'||next==='}'){ out+=next; i+=2; continue; }
      if(next==='\u200b'&&/[Nnh]/.test(text[i+2]||'')){
        out+='\\'+text[i+2]; i+=3; continue;
      }
      if(next==='N'||next==='n'){ out+='\n'; i+=2; continue; }
      if(next==='h'){ out+=' '; i+=2; continue; }
      out+='\\'; i++; continue;
    }
    if(ch==='{'){
      let end=i+1;
      while(end<text.length){
        if(text[end]==='\\'){ end+=2; continue; }
        if(text[end]==='}') break;
        end++;
      }
      if(end<text.length){ i=end+1; continue; }
    }
    out+=ch;
    i++;
  }
  return decodeLegacyLineBreaks(out);
}

/* ===== 2. 字幕格式 解析 / 序列化 ====================================== */
const SubFormats = {
  /* ---- SRT ---- */
  parseSRT(text){
    const out=[]; const blocks=text.replace(/\r/g,'').split(/\n{2,}/);
    for(const blk of blocks){
      const lines=blk.split('\n');
      let i=0; while(i<lines.length && /^\s*\d+\s*$/.test(lines[i]))i++;
      const tline=lines[i]; if(!tline||!tline.includes('-->'))continue;
      const [a,b]=tline.split('-->');
      const start=srtToSec(a), end=srtToSec(b);
      const txt=decodeLegacyLineBreaks(lines.slice(i+1).join('\n')).trim();
      out.push({start,end,text:txt});
    }
    return out;
  },
  toSRT(cues){
    return cues.filter(c=>c.timed!==false).map((c,i)=>
      `${i+1}\n${secToSRT(c.start)} --> ${secToSRT(c.end)}\n${c.text||''}`).join('\n\n').replace(/\r?\n/g, '\r\n')+'\r\n\r\n';
  },
  /* ---- ASS ---- */
  parseASS(text){
    const out=[]; const lines=text.replace(/\r/g,'').split('\n');
    let fmt=null;
    for(const ln of lines){
      const t=ln.trim();
      if(/^Format:/i.test(t) && /Start/i.test(t) && /Text/i.test(t)){
        fmt=t.replace(/^Format:\s*/i,'').split(',').map(s=>s.trim().toLowerCase());
      }
      if(/^Dialogue:/i.test(t)){
        const rest=t.replace(/^Dialogue:\s*/i,'');
        const f=fmt||['layer','start','end','style','name','marginl','marginr','marginv','effect','text'];
        const nText=f.length; // 以欄位數切，text 取剩餘
        const parts=splitN(rest,nText-1);
        const rec={}; f.forEach((k,idx)=>rec[k]=parts[idx]!==undefined?parts[idx]:'');
        const txt=decodeAssDialogueText(rec.text||'').trim();
        let track=0;
        const nm=(rec.name||'').match(/atg?(\d+)/i); if(nm)track=Math.max(0,+nm[1]-1);
        else if(/^\d+$/.test(rec.layer))track=clamp(+rec.layer,0,9);
        out.push({start:assToSec(rec.start),end:assToSec(rec.end),text:txt,track});
      }
    }
    return out;
  },
  toASS(cues,fps,tracks=[],vw=1920,vh=1080, ww=1920, vww=1000, vwh=562){
    const head=
`[Script Info]
; Script generated by SUB Tool
ScriptType: v4.00+
WrapStyle: 0
Collisions: Normal
PlayResX: ${vww}
PlayResY: ${vwh}
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
`;
    // 樣式行/文字轉換一律走 substyle.js（v4.23）：軌道樣式全欄位（字型/粗斜/字距/框線/陰影/直書/背景塊）＋
    // 逐句覆蓋（inline override）＋直書逐字＋行距墊高——與 HTML 預覽同構（同吃 effStyle）。
    let styles = '';
    if (!tracks || !tracks.length) {
      styles += styleToAssStyleLine('Default', effStyle(null, null), vwh) + '\n';
    } else {
      tracks.forEach((tk, i) => { styles += styleToAssStyleLine(`Track${i}`, effStyle(null, tk), vwh) + '\n'; });
      styles += styleToAssStyleLine('Default', effStyle(null, null), vwh) + '\n';
    }

    const eventsHead = `\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n`;
    const vis=cues.filter(c=>{
      if(c.timed===false) return false;
      const tk = c.track || 0;
      if(tracks && tracks[tk] && tracks[tk].visible === false) return false;
      return true;
    });
    // 背景色塊只有 Style 行表達得出來（BorderStyle/BackColour 無 inline tag）→ 有覆蓋到它的句子
    // 各自帶一條專屬 Style。其餘欄位一律走 inline tag，不必為每句生 Style。
    const trkOf = c => (tracks && tracks.length > (c.track||0)) ? tracks[c.track||0] : null;
    const ownStyle = new Map(); // cue.id → Style 名
    for(const c of vis){
      if(!c.style || !STYLE_ONLY_KEYS.some(k => c.style[k] != null)) continue;
      const nm = `Cue_${String(c.id).replace(/[^A-Za-z0-9_]/g,'')}`;
      ownStyle.set(c.id, nm);
      styles += styleToAssStyleLine(nm, effStyle(c, trkOf(c)), vwh) + '\n';
    }
    const body=vis.map(c=>{
      const trk = trkOf(c);
      const st = effStyle(c, trk);
      const styName = ownStyle.get(c.id) || (trk ? `Track${c.track||0}` : 'Default');
      const tags = cueAssTags(c.style);
      const head = `Dialogue: ${c.track||0},${secToASS(c.start, fps)},${secToASS(c.end, fps)},${styName},atg${(c.track||0)+1},0,0,0,,`;
      // 直書：ASS 無 writing-mode → 一列一個 Dialogue、逐列自己定位（見 verticalAssCols）。
      // 每列以 inline \an 覆蓋 Style 的 Alignment（Style 是整軌共用的，做不到逐列）。
      if(st.vertical){
        return verticalAssCols(st, c.text || '', vww, vwh)
          .map(col => `${head}{\\an${col.an}\\pos(${col.x},${col.y})}${tags}${assJoinVertical(col.chars, st)}`)
          .join('\n');
      }
      // \pos 精確落點（畫面百分比座標）＋逐句覆蓋 tags。
      // 錨點預設由 Style 的 Alignment 決定；該句自己覆蓋了對齊 → 補一個 inline \an
      // （Style 是整軌共用的，改它會動到別句）。
      const anOv = (c.style && (c.style.align != null || c.style.valign != null) && !ownStyle.has(c.id))
        ? `{\\an${assAlignN(st)}}` : '';
      // 逐行跳脫後才交給 assJoinLines——它會插入 \N 與 {\fs} 行距墊高，
      // 那些是我們自己要送的控制碼，不能跟使用者文字一起被跳脫。
      const lines = String(c.text || '').replace(/\r/g, '').split('\n').map(assEscapeText);
      return head + anOv + cueAssPos(st, vww, vwh) + tags + assJoinLines(lines, st);
    }).join('\n');
    return head+styles+eventsHead+body+'\n';
  },
  /* ---- Adobe Encore ---- */
  parseEncore(text,fps,df=false){
    const out=[]; const lines=text.replace(/\r/g,'').split('\n');
    const re=/^\s*(\d{1,2}:\d{2}:\d{2}[:;]\d{2}|--:--:--:--)\s+(\d{1,2}:\d{2}:\d{2}[:;]\d{2}|--:--:--:--)\s+(.*)$/;
    let lastTime = 0;
    for(const ln of lines){
      const m=ln.match(re); if(!m)continue;
      const isUntimed = m[1]==='--:--:--:--' || m[2]==='--:--:--:--';
      let start = 0, end = 0;
      if(!isUntimed){
        start = encoreToSec(m[1],fps,df);
        end = encoreToSec(m[2],fps,df);
        lastTime = end;
      } else {
        start = lastTime;
        end = lastTime;
      }
      out.push({
        start, end,
        text: decodeLegacyLineBreaks(m[3].replace(/\s{2,}/g,'\n')).trim(),
        timed: isUntimed ? false : undefined
      });
    }
    return out;
  },
  toEncore(cues,fps,df=false){
    return cues.map(c=>{
      if(c.timed===false) return `--:--:--:-- --:--:--:-- ${(c.text||'').replace(/\n/g,'\\\\')}`;
      return `${secToEncore(c.start,fps,df)} ${secToEncore(c.end,fps,df)} ${(c.text||'').replace(/\n/g,'\\\\')}`;
    }).join('\r\n')+'\r\n';
  },
  /* ---- 純文字 ---- */
  parseTXT(text){
    let t = 0;
    return text.replace(/\r/g,'').split('\n').map(l=>l.trim()).filter(l=>l.length)
      .map(l=>{ const c={start:t,end:t,text:decodeLegacyLineBreaks(l),timed:false}; t+=0.001; return c; });
  },
  toTXT(cues){
    return cues.map(c=>(c.text||'').replace(/\n/g, '\\\\')).join('\n')+'\n';
  }
};
/* 把字串以逗號切成 n 段，第 n 段含其餘全部 */
function splitN(str,n){
  const out=[]; let i=0;
  for(let k=0;k<n;k++){ const j=str.indexOf(',',i); if(j<0){out.push(str.slice(i));return out;} out.push(str.slice(i,j)); i=j+1; }
  out.push(str.slice(i)); return out;
}

export { SubFormats, splitN, decodeLegacyLineBreaks, decodeAssDialogueText };

