/* SUB Tool — 字幕格式 解析 / 序列化（SRT / ASS / Encore / TXT） */
import { clamp } from './util.js';
import { secToSRT, secToASS, secToEncore, srtToSec, assToSec, encoreToSec } from './time.js';

/* ===== 2. 字幕格式 解析 / 序列化 ====================================== */
const SubFormats = {
  /* ---- SRT ---- */
  parseSRT(text){
    const out=[]; const blocks=text.replace(/\r/g,'').split(/\n{2,}/);
    for(const blk of blocks){
      const lines=blk.split('\n').filter(l=>l.length||true);
      let i=0; while(i<lines.length && /^\s*\d+\s*$/.test(lines[i]))i++;
      const tline=lines[i]; if(!tline||!tline.includes('-->'))continue;
      const [a,b]=tline.split('-->');
      const start=srtToSec(a), end=srtToSec(b);
      const txt=lines.slice(i+1).join('\n').trim();
      out.push({start,end,text:txt});
    }
    return out;
  },
  toSRT(cues,fps){
    return cues.filter(c=>c.timed!==false).map((c,i)=>
      `${i+1}\n${secToSRT(c.start)} --> ${secToSRT(c.end)}\n${c.text||''}`).join('\n\n')+'\n';
  },
  /* ---- ASS ---- */
  parseASS(text){
    const out=[]; const lines=text.replace(/\r/g,'').split('\n');
    let fmt=null;
    for(const ln of lines){
      const t=ln.trim();
      if(/^Format:/i.test(t) && /Start/i.test(t) && /Text/i.test(t)){
        fmt=t.replace(/^Format:\s*/i,'').split(',').map(s=>s.trim().toLowerCase());
      }
      if(/^Dialogue:/i.test(t)){
        const rest=t.replace(/^Dialogue:\s*/i,'');
        const f=fmt||['layer','start','end','style','name','marginl','marginr','marginv','effect','text'];
        const nText=f.length; // 以欄位數切，text 取剩餘
        const parts=splitN(rest,nText-1);
        const rec={}; f.forEach((k,idx)=>rec[k]=parts[idx]!==undefined?parts[idx]:'');
        let raw=rec.text||'';
        const txt=raw.replace(/\{[^}]*\}/g,'').replace(/\\N/gi,'\n').replace(/\\h/g,' ').trim();
        let track=0;
        const nm=(rec.name||'').match(/atg?(\d+)/i); if(nm)track=Math.max(0,+nm[1]-1);
        else if(/^\d+$/.test(rec.layer))track=clamp(+rec.layer,0,9);
        out.push({start:assToSec(rec.start),end:assToSec(rec.end),text:txt,track});
      }
    }
    return out;
  },
  toASS(cues,fps){
    const head=
`[Script Info]
; Script generated by SUB Tool
ScriptType: v4.00+
WrapStyle: 0
Collisions: Normal
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,微软雅黑,54,&H00FFFFFF,&H00FFFFFF,&H19533B3B,&H910E0807,0,0,0,0,100.0,100.0,0.0,0.0,1,3.1,1.2,2,135,135,72,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;
    const body=cues.filter(c=>c.timed!==false).map(c=>{
      const txt=(c.text||'').replace(/\n/g,'\\N');
      return `Dialogue: ${c.track||0},${secToASS(c.start)},${secToASS(c.end)},Default,atg${(c.track||0)+1},0,0,0,,${txt}`;
    }).join('\n');
    return head+body+'\n';
  },
  /* ---- Adobe Encore ---- */
  parseEncore(text,fps){
    const out=[]; const lines=text.replace(/\r/g,'').split('\n');
    const re=/^\s*(\d{1,2}:\d{2}:\d{2}[:;]\d{2})\s+(\d{1,2}:\d{2}:\d{2}[:;]\d{2})\s+(.*)$/;
    for(const ln of lines){
      const m=ln.match(re); if(!m)continue;
      out.push({start:encoreToSec(m[1],fps),end:encoreToSec(m[2],fps),text:m[3].replace(/\s{2,}/g,'\n').trim()});
    }
    return out;
  },
  toEncore(cues,fps){
    return cues.filter(c=>c.timed!==false).map(c=>
      `${secToEncore(c.start,fps)} ${secToEncore(c.end,fps)} ${(c.text||'').replace(/\n/g,' ')}`).join('\r\n')+'\r\n';
  },
  /* ---- 純文字 ---- */
  parseTXT(text){
    return text.replace(/\r/g,'').split('\n').map(l=>l.trim()).filter(l=>l.length)
      .map(l=>({start:0,end:0,text:l,timed:false}));
  },
  toTXT(cues){
    return cues.map(c=>(c.text||'')).join('\n')+'\n';
  }
};
/* 把字串以逗號切成 n 段，第 n 段含其餘全部 */
function splitN(str,n){
  const out=[]; let i=0;
  for(let k=0;k<n;k++){ const j=str.indexOf(',',i); if(j<0){out.push(str.slice(i));return out;} out.push(str.slice(i,j)); i=j+1; }
  out.push(str.slice(i)); return out;
}

export { SubFormats, splitN };
